### ISSUE TITLE
TypeAnnotation node

### ISSUE THREAD

**Issue by andy-ms** [JamesHenry/tsep-babylon-test#1]
### Code

```ts
let x: number
```

### Eslint

```json
"type": "TypeAnnotation",
"typeAnnotation": {
  "type": "TSNumberKeyword",
},
```

### Babylon

```json
"type": "TSNumberKeyword",
```

The estree [spec](https://github.com/estree/estree/blob/master/extensions/type-annotations.md#typeannotations) mentions a `TypeAnnotation` interface. But this interface doesn't mention anything about the `type` property of such an object, so it could be that this interface may be a supertype to concrete types such as `TSNumberKeyword`.

**Comment by JamesHenry** [comment]
As well as using the (pretty barebones) ESTree extension you have referenced, another one of the key ideas when starting `typescript-eslint-parser` (hereafter ESLint for brevity) was that we would try and match precedents in Flow ASTs wherever possible.

The idea being that this would allow for easier alignment on future additions to that extensions spec. 

As you can see here:
http://astexplorer.net/#/gist/d7e545d56efd067cc9dbe14df665bd52/bbffc43390f925e3fb60e1598c32fdf4a5fa7bba

...the output from Flow matches what ESLint has produced above.

@andy-ms would you be open to changing the babylon plugin based on this reasoning?
