### ISSUE TITLE
Type parameters

### ISSUE THREAD

**Issue by andy-ms** [JamesHenry/tsep-babylon-test#10]
### Code

```ts
function f<U extends object = {}>() {}
```

### Eslint

```json
"typeParameters": {
  "type": "TypeParameterDeclaration",
  "params": [
    {
      "type": "TypeParameter",
      "name": "U",
      "constraint": {
        "type": "TypeAnnotation",
        "typeAnnotation": {
          "type": "TSObjectKeyword"
        }
      },
      "default": {
        "type": "TSTypeLiteral",
        "members": []
      }
    }
  ]
}
```

### Babylon

```json
"typeParameters": [
  {
    "type": "TSTypeParameterDeclaration",
    "name": {
      "type": "Identifier",
      "name": "U"
    },
    "constraint": {
      "type": "TSObjectKeyword"
    },
    "default": {
      "type": "TSTypeLiteral",
      "members": []
    }
  }
],
```

(Resembles TypeScript's `TypeParameterdeclarationDeclaration`. In TypeScript these are attached directly to the `SignatureDeclaration` in an optional array.)

**Comment by JamesHenry** [comment]
This is another case of us matching the Flow precedent as far as we could.

This particular source is not valid Flow, but Flow does have `TypeParameterDeclaration`s which have an array of `params`, so we are matching that here. That is also why there is no need for the `TS` prefix in the ESLint AST.

**Comment by andy-ms** [comment]
One remaining difference:

eslint:
```json
"name": "T",
````

babylon:
```json
"name": {
  "name": "T",
  "type": "Identifier",
},
```

I see that flow uses `name: "T"` too, but it seems unusual to not have an Identifier node there.

**Comment by andy-ms** [comment]
Also, I've mostly fixed #1, but I noticed that in eslint "constraint" has the TypeAnnotation wrapper but "default" doesn't.
The way flow does this is to have a "bound" which is a TypeAnnotation, so by that logic both "constraint" and "default" should be type annotations.

**Comment by andy-ms** [comment]
Actually, it looks like flow only uses a TypeAnnotation for the `bound` but *not* for the `default`. Now I think that for TypeScript we should use types directly for both `constraint` and `default`.

**Comment by JamesHenry** [comment]
@andy-ms Would you mind briefly summarising what you think the final AST should look like for the original source code here>

**Comment by andy-ms** [comment]
For `function f<T extends object = object>() {}`:

eslint:

```json
"type": "TypeParameterDeclaration",
"params": [
  {
    "type": "TypeParameter",
    "name": "T",
    "constraint": {
      "type": "TypeAnnotation",
      "typeAnnotation": {
        "type": "TSObjectKeyword"
      }
    },
    "default": {
      "type": "TSObjectKeyword"
    }
  }
]
```

babylon:

```json
"type": "TypeParameterDeclaration",
"params": [
  {
    "type": "TypeParameter",
    "name": "T",
    "constraint": {
      "type": "TSObjectKeyword"
    },
    "default": {
      "type": "TSObjectKeyword"
    }
  }
]
```

I think babylon's choice (no "TypeAnnotation" nodes at all) should be preferred, because it is consistent both with itself and with flow's handling of "default".

**Comment by JamesHenry** [comment]
Thanks! I have addressed that here: https://github.com/eslint/typescript-eslint-parser/pull/325
