### ISSUE TITLE
TSQualifiedName

### ISSUE THREAD

**Issue by andy-ms** [JamesHenry/tsep-babylon-test#12]
### Code

```ts
let x: A.B;
```

### Eslint

```json
"type": "TSTypeReference",
"typeName": {
  "type": "JSXMemberExpression",
  "object": {
    "type": "JSXIdentifier",
    "name": "A"
  },
  "property": {
    "type": "JSXIdentifier",
    "name": "B"
  }
}
```

### Babylon

```json
"type": "TSTypeReference",
"typeName": {
  "type": "TSQualifiedName",
  "left": {
    "type": "Identifier",
    "name": "A"
  },
  "right": {
    "type": "Identifier",
    "name": "B"
  }
}
```

**Comment by JamesHenry** [comment]
Ah yes, we recently discovered this here: https://github.com/eslint/typescript-eslint-parser/pull/258

Very good timing, as we hadn't actually resolved a fix yet 😄

**Comment by JamesHenry** [comment]
That has been updated and I have verified the fix. I did find another issue along the way though: https://github.com/JamesHenry/tsep-babylon-test/issues/19
