### ISSUE TITLE
"access" vs "accessibility"

### ISSUE THREAD

**Issue by andy-ms** [JamesHenry/tsep-babylon-test#14]
### Code

```ts
class C {
    public x;
}
```

### Eslint

```json
"accessibility": "public",
```

### Babylon

```json
"access": "public",
```

**Comment by andy-ms** [comment]
This is now fixed in my WIP branch.

**Comment by JamesHenry** [comment]
Thanks a lot for changing that so quickly! I agree for trivial differences like this, it is practical to go with the ESLint implementation if possible 👍
