### ISSUE TITLE
null type

### ISSUE THREAD

**Issue by andy-ms** [JamesHenry/tsep-babylon-test#16]
### Code

```ts
let x: null;
```

### Eslint

```json
"raw": "null",
"type": "Literal",
"value": null
```

### Babylon

```json
"type": "TSNullKeyword"
```

(Resembles TypeScript's `KeywordTypeNode` with `NullKeyword`)

**Comment by soda0289** [comment]
This should be changed in eslint parser

**Comment by JamesHenry** [comment]
Fixed in https://github.com/eslint/typescript-eslint-parser/pull/313
