### ISSUE TITLE
Difference in range end (and column) data for Identifiers with types

### ISSUE THREAD

**Issue by JamesHenry** [JamesHenry/tsep-babylon-test#19]
### Code

```ts
let x: string;
```

### Eslint

```json
"type": "Identifier",
"name": "x",
"loc": {
  "end": {
    "column": 5
  }
},
"range": [
  4,
  5
]
```

### Babylon

```json
"type": "Identifier",
"name": "x",
"loc": {
  "end": {
    "column": 10
  }
},
"range": [
  4,
  10
]
```

Essentially ESLint does not include the typeAnnotation's length, babylon does. Surprised we haven't noticed this before 😄 

It is possible (although I cannot remember) that we decided not to include the typeAnnotation in the Identifier's length so as not to conflict with some assumptions made in ESLint rules...

I can see that Flow does include the typeAnnotation's in the Identifier's length, and therefore aligns with babylon here.

**Comment by andy-ms** [comment]
I think a parent range should always contain its children's ranges though...
It's unfortunate that an Identifier can have children, but since it can, then the "name" property should essentially be treated as a child whose range is `pos` to `pos + name.length`.

**Comment by vjeux** [comment]
> I think a parent range should always contain its children's ranges though...

Agreed, a place where it's not the case is for decorators. It's breaking prettier comment attaching logic because we don't go down the parent since it doesn't include the child position.
