### ISSUE TITLE
Namespace: `body` vs `statements`

### ISSUE THREAD

**Issue by andy-ms** [JamesHenry/tsep-babylon-test#2]
### Code

```ts
namespace N {}
```

### Eslint

```json
"body": [],
```

(Resembles `BlockStatement`)

### Babylon

```json
"statements": [],
```

(Resembles TypeScript's `NamespaceDeclaration`)

**Comment by JamesHenry** [comment]
We simply felt that `body` was a better fit for ESTree nodes, I don't believe anything in ESTree has a `statements` property...

**Comment by soda0289** [comment]
Also there was an eslint rule in the `eslint-plugin-import` that was failing because it expected `import` and `export` statements to be inside a `body` property.
