### ISSUE TITLE
Interface ".body.body" vs ".members"

### ISSUE THREAD

**Issue by andy-ms** [JamesHenry/tsep-babylon-test#3]
### Code

```ts
interface I {}
```

### Eslint

```json
"body": {
  "body": [],
  "type": "TSInterfaceBody",
},
```

(Resembles `ClassDeclaration`)

### Babylon

```json
"members": []
```

(Resembles TypeScript's `InterfaceDeclaration`)

**Comment by JamesHenry** [comment]
We made this update to interfaces about two weeks ago: https://github.com/eslint/typescript-eslint-parser/pull/241

As with the `namespace` difference, I think on our side we were just trying to make the node as "ESTree-like" as possible. AFAIK there are currently no ESTree nodes with `members`.

I will let @soda0289 comment further if he wishes as it was his PR.

**Comment by soda0289** [comment]
This property change from `memebers` to body was allow it to be more estree like. The fact that interfaces can extend other interfaces, similar to classes, is the reason for breaking it up into two nodes `TSInterfaceDeclaration` and `TSInterfaceBody`. This separation makes it easier to create eslint rules that behave the same way as classes do with different brace or indent styles.

**Comment by JamesHenry** [comment]
One thing that just occurred to me is that Flow added interfaces not too long ago. I had never checked their AST for interfaces before now: http://astexplorer.net/#/gist/fb1306928bef0ccb99ac99a37c721a17/7cb91294218d78765470ca9104de06277baf0414

They use `body.properties` as they using an `ObjectTypeAnnotation` node.
